# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{event-engine}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ed Howland"]
  s.date = %q{2010-03-27}
  s.description = %q{Pure Ruby Event Dispatcher}
  s.email = %q{ed.howland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardoc/checksums",
     ".yardoc/objects/AlwaysInterested.dat",
     ".yardoc/objects/AlwaysInterested/interested_3F_i.dat",
     ".yardoc/objects/EventEngine.dat",
     ".yardoc/objects/EventEngine/Engine.dat",
     ".yardoc/objects/EventEngine/Engine/dispatch_i.dat",
     ".yardoc/objects/EventEngine/Engine/eventq_3D_i.dat",
     ".yardoc/objects/EventEngine/Engine/eventq_i.dat",
     ".yardoc/objects/EventEngine/Engine/fiber_3D_i.dat",
     ".yardoc/objects/EventEngine/Engine/fiber_i.dat",
     ".yardoc/objects/EventEngine/Engine/handle_i.dat",
     ".yardoc/objects/EventEngine/Engine/handlers_3D_i.dat",
     ".yardoc/objects/EventEngine/Engine/handlers_i.dat",
     ".yardoc/objects/EventEngine/Engine/initialize_i.dat",
     ".yardoc/objects/EventEngine/Engine/run_i.dat",
     ".yardoc/objects/EventEngine/Engine/trigger_i.dat",
     ".yardoc/objects/root.dat",
     ".yardoc/proxy_types",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/AlwaysInterested.html",
     "doc/EventEngine.html",
     "doc/EventEngine/Engine.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "example/dirtree.rb",
     "features/event-engine.feature",
     "features/step_definitions/event-engine_steps.rb",
     "features/support/env.rb",
     "lib/event-engine.rb",
     "lib/event-engine/event_engine.rb",
     "spec/event-engine_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/edhowland/event-engine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Pure Ruby Event Dispatcher}
  s.test_files = [
    "spec/event-engine_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

